In [523]:
import pandas as pd

In [534]:
df = pd.read_excel('./data.gov.ru/электр_оборудование.xlsx')

In [535]:
df = df.iloc[1:]
df.columns = df.iloc[1]
df

In [536]:
df

2,Наименование,январь,февраль,март,апрель,май,июнь,июль,август,сентябрь,октябрь,ноябрь,декабрь
1,NaN,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Наименование,январь,февраль,март,апрель,май,июнь,июль,август,сентябрь,октябрь,ноябрь,декабрь
3,"Электродвигатели мощностью не более 37,5 Вт; э...",86649,93954,96126,79270,77595,63674,70807,73790,67963,77346,82259,86905
4,Электродвигатели переменного и постоянного ток...,19740,24190,28456,24830,20525,31130,33507,33769,19660,15409,16157,21914
5,Электродвигатели переменного тока многофазные ...,3508,3787,5455,5459,10408,4980,5552,6003,6676,21990,10306,8030
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,"Вагоны-цистерны, штук",439,491,551,596,512,246,343,479,743,745,659,632
297,"Вертолеты, штук",-,3,6,9,2,10,13,12,7,10,8,16
298,"Самолеты гражданские, штук",-,1,-,6,-,5,2,-,1,1,6,5
299,"Мотоциклы и мотоциклетные коляски, штук",64,135,118,6,72,99,144,123,114,126,127,149
300,"Велосипеды двухколесные и прочие, без двигател...",111973,126982,124390,56752,84433,133933,115505,9896,34511,57588,87363,111589

In [532]:
str1 = 'компы_электроника_оптика'
dfFinal.to_csv('./' + str1 + '/' + str1 + '.csv')
df2017.set_index('Наименование').to_csv('./' + str1 + '/' + str1 + '2017.csv')
df2018.set_index('Наименование').to_csv('./' + str1 + '/' + str1 + '2018.csv')
df2019.set_index('Наименование').to_csv('./' + str1 + '/' + str1 + '2019.csv')
df2020.set_index('Наименование').to_csv('./' + str1 + '/' + str1 + '2020.csv')

In [537]:

df2017 = pd.DataFrame()
df2018 = pd.DataFrame()
df2019 = pd.DataFrame()
df2020 = pd.DataFrame()
df2021 = pd.DataFrame()

tmp1 = 0
tmp2 = 0
fl = 0
year = 2017
for i in range(df.index[0] + 1, df.index[0] + df.shape[0]):
    if df.loc[i]['Наименование'] == 'Наименование':
        if df.loc[i - 1]['январь'] == 2017 and i > df.index[0] + 5:
            tmp2 = i - 5
            dfNew = pd.DataFrame()
            dfNew = df.loc[tmp2 + 4:]
            print(tmp2)
            fl = 1
        else:
            tmp2 = i - 2
        if tmp1 != 0:
            if year == 2017:
                df2017 = df.loc[tmp1:tmp2]
            if year == 2018:
                df2018 = df.loc[tmp1:tmp2]
            if year == 2019:
                df2019 = df.loc[tmp1:tmp2]
            if year == 2020:
                df2020 = df.loc[tmp1:tmp2]
            if year == 2021:
                df2021 = df.loc[tmp1:tmp2]
            year += 1
        tmp1 = i + 1
        if fl == 1 and df.index[0] + 3:
            break
    df2020 = df.loc[tmp1:]

df2017 = df2017.dropna()
df2018 = df2018.dropna()
df2019 = df2019.dropna()
df2020 = df2020.dropna()
#df2017.drop(df2017.tail(1).index,inplace=True)
#df2018.drop(df2018.tail(1).index,inplace=True)
#df2019.drop(df2019.tail(1).index,inplace=True)
#df2020.drop(df2020.tail(1).index,inplace=True)
df2017 = df2017.replace(' - ', 0)
df2018 = df2018.replace(' - ', 0)
df2019 = df2019.replace(' - ', 0)
df2020 = df2020.replace(' - ', 0)
df2017 = df2017.replace('- ', 0)
df2018 = df2018.replace('- ', 0)
df2019 = df2019.replace('- ', 0)
df2020 = df2020.replace('- ', 0)
df2017 = df2017.replace(' -', 0)
df2018 = df2018.replace(' -', 0)
df2019 = df2019.replace(' -', 0)
df2020 = df2020.replace(' -', 0)
df2017 = df2017.replace('-', 0)
df2018 = df2018.replace('-', 0)
df2019 = df2019.replace('-', 0)
df2020 = df2020.replace('-', 0)
for column in df2017.columns[1:]:
    df2017[column] = df2017[column].astype('int64')
for column in df2018.columns[1:]:
    df2018[column] = df2018[column].astype('int64')
for column in df2019.columns[1:]:
    df2019[column] = df2019[column].astype('int64')
for column in df2020.columns[1:]:
    df2020[column] = df2020[column].astype('int64')
for column in df2021.columns[1:]:
    df2021[column] = df2021[column].astype('int64')
    
#Указать новое имя
dfFinal = pd.DataFrame(index=df2017['Наименование'], columns=[2017,2018,2019,2020])

i = 0
for index, row in dfFinal.iterrows():
    row[2017] = df2017.reset_index().sum(axis=1)[i]
    row[2018] = df2018.reset_index().sum(axis=1)[i]
    row[2019] = df2019.reset_index().sum(axis=1)[i]
    row[2020] = df2020.reset_index().sum(axis=1)[i]
    i += 1

df = dfNew.copy()

83

KeyError: 18

In [505]:
#version 2
df = df.iloc[1:]
df.columns = df.iloc[1]

df2017 = pd.DataFrame()
df2018 = pd.DataFrame()
df2019 = pd.DataFrame()
df2020 = pd.DataFrame()
df2021 = pd.DataFrame()

tmp1 = 0
tmp2 = 0
fl = 0
year = 2017
for i in range(df.index[0] + 1, df.index[0] + df.shape[0]):
    if df.loc[i]['Наименование'] == 'Наименование':
        if df.loc[i - 1]['январь'] == 2017 and i > df.index[0] + 5:
            tmp2 = i - 5
            dfNew = pd.DataFrame()
            dfNew = df.loc[tmp2 + 4:]
            print(tmp2)
            fl = 1
        else:
            tmp2 = i - 2
        if tmp1 != 0:
            if year == 2017:
                df2017 = df.loc[tmp1:tmp2]
            if year == 2018:
                df2018 = df.loc[tmp1:tmp2]
            if year == 2019:
                df2019 = df.loc[tmp1:tmp2]
            if year == 2020:
                df2020 = df.loc[tmp1:tmp2]
            if year == 2021:
                df2021 = df.loc[tmp1:tmp2]
            year += 1
        tmp1 = i + 1
        if fl == 1 and df.index[0] + 3:
            break

df2017 = df2017.replace(' - ', 0)
df2018 = df2018.replace(' - ', 0)
df2019 = df2019.replace(' - ', 0)
df2020 = df2020.replace(' - ', 0)
df2017 = df2017.replace('- ', 0)
df2018 = df2018.replace('- ', 0)
df2019 = df2019.replace('- ', 0)
df2020 = df2020.replace('- ', 0)
df2017 = df2017.replace(' -', 0)
df2018 = df2018.replace(' -', 0)
df2019 = df2019.replace(' -', 0)
df2020 = df2020.replace(' -', 0)
for column in df2017.columns[1:]:
    df2017[column] = df2017[column].astype('int64')
for column in df2018.columns[1:]:
    df2018[column] = df2018[column].astype('int64')
for column in df2019.columns[1:]:
    df2019[column] = df2019[column].astype('int64')
for column in df2020.columns[1:]:
    df2020[column] = df2020[column].astype('int64')
for column in df2021.columns[1:]:
    df2021[column] = df2021[column].astype('int64')
    
#Указать новое имя
dfCompElectric = pd.DataFrame(index=df2017['Наименование'], columns=[2017,2018,2019,2020])

i = 0
for index, row in dfCompElectric.iterrows():
    row[2017] = df2017.reset_index().sum(axis=1)[i]
    row[2018] = df2018.reset_index().sum(axis=1)[i]
    row[2019] = df2019.reset_index().sum(axis=1)[i]
    row[2020] = df2020.reset_index().sum(axis=1)[i]
    i += 1

df = dfNew.copy()

24

In [486]:
tmp1 = 0
tmp2 = 0
fl = 0
year = 2017
for i in range(df.index[0] + 1, df.index[0] + df.shape[0]):
    if df.loc[i]['Наименование'] == 'Наименование':
        if df.loc[i - 1]['январь'] == 2017 and i > df.index[0] + 5:
            tmp2 = i - 5
            dfNew = pd.DataFrame()
            dfNew = df.loc[tmp2 + 4:]
            print(tmp2)
            fl = 1
        else:
            tmp2 = i - 2
        if tmp1 != 0:
            if year == 2017:
                df2017 = df.loc[tmp1:tmp2]
            if year == 2018:
                df2018 = df.loc[tmp1:tmp2]
            if year == 2019:
                df2019 = df.loc[tmp1:tmp2]
            if year == 2020:
                df2020 = df.loc[tmp1:tmp2]
            if year == 2021:
                df2021 = df.loc[tmp1:tmp2]
            year += 1
        tmp1 = i + 1
        if fl == 1 and df.index[0] + 3:
            break

df2017 = df2017.replace(' - ', 0)
df2018 = df2018.replace(' - ', 0)
df2019 = df2019.replace(' - ', 0)
df2020 = df2020.replace(' - ', 0)
df2017 = df2017.replace('- ', 0)
df2018 = df2018.replace('- ', 0)
df2019 = df2019.replace('- ', 0)
df2020 = df2020.replace('- ', 0)
df2017 = df2017.replace(' -', 0)
df2018 = df2018.replace(' -', 0)
df2019 = df2019.replace(' -', 0)
df2020 = df2020.replace(' -', 0)
for column in df2017.columns[1:]:
    df2017[column] = df2017[column].astype('int64')
for column in df2018.columns[1:]:
    df2018[column] = df2018[column].astype('int64')
for column in df2019.columns[1:]:
    df2019[column] = df2019[column].astype('int64')
for column in df2020.columns[1:]:
    df2020[column] = df2020[column].astype('int64')
for column in df2021.columns[1:]:
    df2021[column] = df2021[column].astype('int64')
    
#Указать новое имя
dfElectricOborud = pd.DataFrame(index=df2017['Наименование'], columns=[2017,2018,2019,2020])

i = 0
for index, row in dfElectricOborud.iterrows():
    row[2017] = df2017.reset_index().sum(axis=1)[i]
    row[2018] = df2018.reset_index().sum(axis=1)[i]
    row[2019] = df2019.reset_index().sum(axis=1)[i]
    if df2020.reset_index().sum(axis=1).shape[0] > i:
        row[2020] = df2020.reset_index().sum(axis=1)[i]
    i += 1

df = dfNew.copy()

110

In [487]:
tmp1 = 0
tmp2 = 0
fl = 0
year = 2017
for i in range(df.index[0] + 1, df.index[0] + df.shape[0]):
    if df.loc[i]['Наименование'] == 'Наименование':
        if df.loc[i - 1]['январь'] == 2017 and i > df.index[0] + 5:
            tmp2 = i - 5
            dfNew = pd.DataFrame()
            dfNew = df.loc[tmp2 + 4:]
            print(tmp2)
            fl = 1
        else:
            tmp2 = i - 2
        if tmp1 != 0:
            if year == 2017:
                df2017 = df.loc[tmp1:tmp2]
            if year == 2018:
                df2018 = df.loc[tmp1:tmp2]
            if year == 2019:
                df2019 = df.loc[tmp1:tmp2]
            if year == 2020:
                df2020 = df.loc[tmp1:tmp2]
            if year == 2021:
                df2021 = df.loc[tmp1:tmp2]
            year += 1
        tmp1 = i + 1
        if fl == 1:
            break

df2017 = df2017.replace(' - ', 0)
df2018 = df2018.replace(' - ', 0)
df2019 = df2019.replace(' - ', 0)
df2020 = df2020.replace(' - ', 0)
df2017 = df2017.replace('- ', 0)
df2018 = df2018.replace('- ', 0)
df2019 = df2019.replace('- ', 0)
df2020 = df2020.replace('- ', 0)
df2017 = df2017.replace(' -', 0)
df2018 = df2018.replace(' -', 0)
df2019 = df2019.replace(' -', 0)
df2020 = df2020.replace(' -', 0)
for column in df2017.columns[1:]:
    df2017[column] = df2017[column].astype('int64')
for column in df2018.columns[1:]:
    df2018[column] = df2018[column].astype('int64')
for column in df2019.columns[1:]:
    df2019[column] = df2019[column].astype('int64')
for column in df2020.columns[1:]:
    df2020[column] = df2020[column].astype('int64')
for column in df2021.columns[1:]:
    df2021[column] = df2021[column].astype('int64')
    
#Указать новое имя
dfMachin = pd.DataFrame(index=df2017['Наименование'], columns=[2017,2018,2019,2020])

i = 0
for index, row in dfMachin.iterrows():
    row[2017] = df2017.reset_index().sum(axis=1)[i]
    row[2018] = df2018.reset_index().sum(axis=1)[i]
    row[2019] = df2019.reset_index().sum(axis=1)[i]
    if df2020.reset_index().sum(axis=1).shape[0] > i:
        row[2020] = df2020.reset_index().sum(axis=1)[i]
    i += 1

df = dfNew.copy()

224

In [488]:
tmp1 = 0
tmp2 = 0
fl = 0
year = 2017
for i in range(df.index[0] + 1, df.index[0] + df.shape[0]):
    if df.loc[i]['Наименование'] == 'Наименование':
        if df.loc[i - 1]['январь'] == 2017 and i > df.index[0] + 5:
            tmp2 = i - 5
            dfNew = pd.DataFrame()
            dfNew = df.loc[tmp2 + 4:]
            print(tmp2)
            fl = 1
        else:
            tmp2 = i - 2
        if tmp1 != 0:
            if year == 2017:
                df2017 = df.loc[tmp1:tmp2]
            if year == 2018:
                df2018 = df.loc[tmp1:tmp2]
            if year == 2019:
                df2019 = df.loc[tmp1:tmp2]
            if year == 2020:
                df2020 = df.loc[tmp1:tmp2]
            if year == 2021:
                df2021 = df.loc[tmp1:tmp2]
            year += 1
        tmp1 = i + 1
        if fl == 1:
            break

df2017 = df2017.replace(' - ', 0)
df2018 = df2018.replace(' - ', 0)
df2019 = df2019.replace(' - ', 0)
df2020 = df2020.replace(' - ', 0)
df2017 = df2017.replace('- ', 0)
df2018 = df2018.replace('- ', 0)
df2019 = df2019.replace('- ', 0)
df2020 = df2020.replace('- ', 0)
df2017 = df2017.replace(' -', 0)
df2018 = df2018.replace(' -', 0)
df2019 = df2019.replace(' -', 0)
df2020 = df2020.replace(' -', 0)
for column in df2017.columns[1:]:
    df2017[column] = df2017[column].astype('int64')
for column in df2018.columns[1:]:
    df2018[column] = df2018[column].astype('int64')
for column in df2019.columns[1:]:
    df2019[column] = df2019[column].astype('int64')
for column in df2020.columns[1:]:
    df2020[column] = df2020[column].astype('int64')
for column in df2021.columns[1:]:
    df2021[column] = df2021[column].astype('int64')
    
#Указать новое имя
dfAutoTransp = pd.DataFrame(index=df2017['Наименование'], columns=[2017,2018,2019,2020])

i = 0
for index, row in dfAutoTransp.iterrows():
    row[2017] = df2017.reset_index().sum(axis=1)[i]
    row[2018] = df2018.reset_index().sum(axis=1)[i]
    row[2019] = df2019.reset_index().sum(axis=1)[i]
    if df2020.reset_index().sum(axis=1).shape[0] > i:
        row[2020] = df2020.reset_index().sum(axis=1)[i]
    i += 1

df = dfNew.copy()

276

In [489]:
tmp1 = 0
tmp2 = 0
fl = 0
year = 2017
for i in range(df.index[0] + 1, df.index[0] + df.shape[0]):
    if df.loc[i]['Наименование'] == 'Наименование':
        if df.loc[i - 1]['январь'] == 2017 and i > df.index[0] + 5:
            tmp2 = i - 5
            dfNew = pd.DataFrame()
            dfNew = df.loc[tmp2 + 4:]
            print(tmp2)
            fl = 1
        else:
            tmp2 = i - 2
        if tmp1 != 0:
            if year == 2017:
                df2017 = df.loc[tmp1:tmp2]
            if year == 2018:
                df2018 = df.loc[tmp1:tmp2]
            if year == 2019:
                df2019 = df.loc[tmp1:tmp2]
            if year == 2020:
                df2020 = df.loc[tmp1:tmp2]
            if year == 2021:
                df2021 = df.loc[tmp1:tmp2]
            year += 1
        tmp1 = i + 1
        if fl == 1:
            break
    df2020 = df.loc[tmp1:]

df2017 = df2017.replace(' - ', 0)
df2018 = df2018.replace(' - ', 0)
df2019 = df2019.replace(' - ', 0)
df2020 = df2020.replace(' - ', 0)
df2017 = df2017.replace('- ', 0)
df2018 = df2018.replace('- ', 0)
df2019 = df2019.replace('- ', 0)
df2020 = df2020.replace('- ', 0)
df2017 = df2017.replace(' -', 0)
df2018 = df2018.replace(' -', 0)
df2019 = df2019.replace(' -', 0)
df2020 = df2020.replace(' -', 0)
for column in df2017.columns[1:]:
    df2017[column] = df2017[column].astype('int64')
for column in df2018.columns[1:]:
    df2018[column] = df2018[column].astype('int64')
for column in df2019.columns[1:]:
    df2019[column] = df2019[column].astype('int64')
for column in df2020.columns[1:]:
    df2020[column] = df2020[column].astype('int64')
for column in df2021.columns[1:]:
    df2021[column] = df2021[column].astype('int64')
    
#Указать новое имя
dfOtherTransp = pd.DataFrame(index=df2017['Наименование'], columns=[2017,2018,2019,2020])

i = 0
for index, row in dfOtherTransp.iterrows():
    row[2017] = df2017.reset_index().sum(axis=1)[i]
    row[2018] = df2018.reset_index().sum(axis=1)[i]
    row[2019] = df2019.reset_index().sum(axis=1)[i]
    if df2020.reset_index().sum(axis=1).shape[0] > i:
        row[2020] = df2020.reset_index().sum(axis=1)[i]
    i += 1

df = dfNew.copy()

In [497]:
dfAutoTransp

,2017,2018,2019,2020
Наименование,,,,
"Двигатели внутреннего сгорания для автотранспортных средств, штук",307242,359225,337428,294599
"Автомобили легковые, штук",1355911,1565742,1525203,1261866
"Автобусы (включая средства автотранспортные пассажирские с числом мест для сидения не менее 10 прочие), штук",40977,46086,14599,13855
"Троллейбусы, штук",483,426,25491,21475
"Средства автотранспортные грузовые, штук",163148,157742,446,589
"Автокраны, штук",2966,3188,156059,143383
"Автомобили пожарные, штук",1172,1277,3226,3062
"Средства транспортные для коммунального хозяйства и содержания дорог, штук",4311,5370,1370,1265
"Прицепы и полуприцепы, технически допустимая максимальная масса которых не более 0,75 т, штук",81953,88947,6921,5347
"Прицепы и полуприцепы тракторные, штук",7187,6412,125438,167856

In [499]:
dfAutoTransp.to_csv('automobile.csv')

In [498]:
dfOtherTransp.to_csv('other_transport.csv')

In [500]:
dfCompElectric.to_csv('computers_electronic_optic.csv')

In [501]:
dfElectricOborud.to_csv('electronic_equipment.csv')

In [502]:
dfMachin.to_csv('machines.csv')